site_name: Fenswood Volcano Tutorial
theme: readthedocs
repo_url: https://github.com/StarlingUAS/fenswood_volcano_template
site_description: 'Fenswood Volcano Template Project'
docs_dir: 'tutorial'
copyright: Copyright &copy; 2021 University of Bristol Flight Laboratory

markdown_extensions:
  - toc:
      permalink: True

plugins:
  - search
  - macros
  - enumerate-headings:
      toc_depth: 3

nav:
  - "Tutorials":
    - "1. Getting Started": 'tutorial/getting_started.md'
    - "2. Controlling a Drone using Mavlink Over ROS": 'tutorial/drone_control.md'
    - "3. An Old-School Example": 'tutorial/old_school.md'
    - "4. Implementing the contorller as a class" : 'tutorial/simple_class.md'
    - "5. A More Modular Controller": 'tutorial/modular.md'
    - "6. Adding A Finite State Machine": 'tutorial/finite_state.md'
    - "7. Using A Ros Timer": 'tutorial/ros_timer.md'
    - "8. Adding Perception": 'tutorial/perception.md'
    - "9. Conclusion and Next Steps": 'tutorial/conclusion.md'
  - "Advanced Tutorials":
    - "1. Brief Starling Introduction": 'advanced/starling.md'
    - "2. Packaging your controller into a container  ": 'advanced/containers.md'